import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { RentBill, UtilityBill, Room, Property, Tenant } from '~/stores/kos'

export const usePdfReceipt = () => {
    const formatCurrency = (val: number | string) => {
        return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(Number(val))
    }

    const _createDoc = (property: Property, room: Room, tenant: Tenant | null, title: string, billNo: string, date: Date | string, isPaid: boolean) => {
        const doc = new jsPDF()
        
        // --- Header ---
        doc.setFontSize(18)
        doc.text(property.name, 14, 15)
        
        doc.setFontSize(10)
        doc.setTextColor(100)
        doc.text(property.address, 14, 21)
        doc.text(`Room: ${room.name}`, 14, 26)
        
        if (tenant) {
            doc.text(`Tenant: ${tenant.name}`, 14, 31)
        }

        // --- Info (Right Aligned) ---
        const pageWidth = doc.internal.pageSize.width
        doc.setFontSize(12)
        doc.setTextColor(0)
        doc.text(title.toUpperCase(), pageWidth - 14, 15, { align: 'right' })
        
        doc.setFontSize(10)
        doc.setTextColor(100)
        doc.text(`No: ${billNo.slice(0, 8).toUpperCase()}`, pageWidth - 14, 21, { align: 'right' })
        doc.text(`Date: ${new Date(date).toLocaleDateString('id-ID')}`, pageWidth - 14, 26, { align: 'right' })
        
        const status = isPaid ? 'PAID' : 'UNPAID'
        doc.setTextColor(isPaid ? 'green' : 'red')
        doc.text(status, pageWidth - 14, 31, { align: 'right' })

        return doc
    }

    const _finalizeDoc = (doc: jsPDF, filename: string) => {
        try {
            const pageWidth = doc.internal.pageSize.width
            const finalY = (doc as any).lastAutoTable.finalY + 10
            doc.setTextColor(150)
            doc.setFontSize(8)
            doc.text('Thank you for your payment.', 14, finalY)
            doc.text('Generated by KostMan', pageWidth - 14, finalY, { align: 'right' })
            doc.save(filename)
        } catch (error) {
            console.error('PDF generation error:', error)
            throw new Error('Gagal membuat PDF. Pastikan browser mendukung download file.')
        }
    }

    const generateRentReceipt = (bill: RentBill, room: Room, property: Property, tenant: Tenant | null) => {
        if (!bill || !room || !property) {
            console.error('Missing required data for rent receipt:', { bill, room, property })
            throw new Error('Data tidak lengkap untuk membuat receipt')
        }
        
        const doc = _createDoc(property, room, tenant, bill.isPaid ? 'RENT RECEIPT' : 'RENT INVOICE', bill.id, bill.generatedAt, bill.isPaid)

        const tableBody = [
            ['Description', 'Detail', 'Amount'],
            ['Room Rent', `${bill.monthsCovered || 1} Month(s)`, formatCurrency(Number(bill.roomPrice) * (bill.monthsCovered || 1))]
        ]

        autoTable(doc, {
            startY: 40,
            head: [['Item', 'Description', 'Total']],
            body: tableBody,
            foot: [['TOTAL', '', formatCurrency(bill.totalAmount)]],
            theme: 'grid',
            headStyles: { fillColor: [66, 66, 66] },
            footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' },
            columnStyles: { 2: { halign: 'right' } }
        })

        _finalizeDoc(doc, `RentBill-${room.name}-${bill.period}.pdf`)
    }

    const generateUtilityReceipt = (bill: UtilityBill, room: Room, property: Property, tenant: Tenant | null) => {
        if (!bill || !room || !property) {
            console.error('Missing required data for utility receipt:', { bill, room, property })
            throw new Error('Data tidak lengkap untuk membuat receipt')
        }
        
        const doc = _createDoc(property, room, tenant, bill.isPaid ? 'UTILITY RECEIPT' : 'UTILITY INVOICE', bill.id, bill.generatedAt, bill.isPaid)

        const tableBody = [
            ['Electricity', `${bill.meterStart} -> ${bill.meterEnd} (${bill.meterEnd - bill.meterStart} kWh @ ${bill.costPerKwh})`, formatCurrency(bill.usageCost)],
            ['Water Fee', 'Flat Rate', formatCurrency(bill.waterFee)],
        ]

        if (Number(bill.trashFee) > 0) {
            tableBody.push(['Trash Fee', 'Monthly', formatCurrency(bill.trashFee)])
        }
        if (Number(bill.additionalCost) > 0) {
            tableBody.push(['Additional Cost', '-', formatCurrency(bill.additionalCost)])
        }

        autoTable(doc, {
            startY: 40,
            head: [['Item', 'Description', 'Amount']],
            body: tableBody,
            foot: [['TOTAL', '', formatCurrency(bill.totalAmount)]],
            theme: 'grid',
            headStyles: { fillColor: [66, 66, 66] },
            footStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' },
            columnStyles: { 2: { halign: 'right' } }
        })

        _finalizeDoc(doc, `UtilityBill-${room.name}-${bill.period}.pdf`)
    }

    const generateCombinedReceipt = (rentBill: RentBill | null, utilBill: UtilityBill | null, room: Room, property: Property, tenant: Tenant | null) => {
        // Determine main info from available bill
        const mainBill = rentBill || utilBill
        if (!mainBill) {
            console.error('No bill data provided for combined receipt')
            throw new Error('Tidak ada data tagihan untuk dicetak')
        }
        
        if (!room || !property) {
            console.error('Missing required data for combined receipt:', { room, property })
            throw new Error('Data kamar atau properti tidak lengkap')
        }

        const isFullyPaid = (rentBill ? rentBill.isPaid : true) && (utilBill ? utilBill.isPaid : true)
        const hasUnpaid = (rentBill && !rentBill.isPaid) || (utilBill && !utilBill.isPaid)
        
        // Simplified title logic
        let title = isFullyPaid ? 'PAYMENT RECEIPT' : 'INVOICE'

        const doc = _createDoc(property, room, tenant, title, mainBill.id, mainBill.generatedAt, isFullyPaid)

        // Override status for better clarity
        if (hasUnpaid) {
            const pageWidth = doc.internal.pageSize.width
            doc.setFontSize(10)
            doc.setTextColor(220, 53, 69) // Red
            doc.text('UNPAID', pageWidth - 14, 31, { align: 'right' })
        }

        const tableBody: any[] = []

        // 1. Rent Section
        if (rentBill) {
            tableBody.push([{ content: 'RENT CHARGES', colSpan: 3, styles: { fontStyle: 'bold', fillColor: [240, 240, 240] } }])
            tableBody.push(['Room Rent', `${rentBill.monthsCovered || 1} Month(s)`, formatCurrency(Number(rentBill.roomPrice) * (rentBill.monthsCovered || 1))])
            if (!rentBill.isPaid) {
                // Optional: mark specific item as unpaid? autoTable doesn't support easy styling per row easily without hooks.
                // We'll just list them.
            }
        }

        // 2. Utility Section
        if (utilBill) {
            tableBody.push([{ content: 'UTILITY CHARGES', colSpan: 3, styles: { fontStyle: 'bold', fillColor: [240, 240, 240] } }])
            tableBody.push(['Electricity', `${utilBill.meterStart} -> ${utilBill.meterEnd} (${utilBill.meterEnd - utilBill.meterStart} kWh)`, formatCurrency(utilBill.usageCost)])
            tableBody.push(['Water Fee', 'Flat Rate', formatCurrency(utilBill.waterFee)])
            if (Number(utilBill.trashFee) > 0) tableBody.push(['Trash Fee', 'Monthly', formatCurrency(utilBill.trashFee)])
            if (Number(utilBill.additionalCost) > 0) tableBody.push(['Additional Cost', '-', formatCurrency(utilBill.additionalCost)])
        }

        const totalRent = rentBill ? Number(rentBill.totalAmount) : 0
        const totalUtil = utilBill ? Number(utilBill.totalAmount) : 0
        const grandTotal = totalRent + totalUtil

        autoTable(doc, {
            startY: 40,
            head: [['Item', 'Description', 'Amount']],
            body: tableBody,
            foot: [['GRAND TOTAL', '', formatCurrency(grandTotal)]],
            theme: 'grid',
            headStyles: { fillColor: [66, 66, 66] },
            footStyles: { fillColor: [50, 50, 50], textColor: [255, 255, 255], fontStyle: 'bold' },
            columnStyles: { 2: { halign: 'right' } }
        })

        _finalizeDoc(doc, `Statement-${room.name}-${mainBill.period}.pdf`)
    }

    return {
        generateRentReceipt,
        generateUtilityReceipt,
        generateCombinedReceipt
    }
}
